"""
MCP Server 4 – Distributor Integration Server
Real-time distributor inventory visibility and automated order placement.
Top 8 distributors via REST API (~70% of volume).
Remaining distributors via structured email / portal automation.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any
import httpx

from config.settings import settings
from utils.logger import get_logger

logger = get_logger("mcp.distributor")


@dataclass
class DistributorStock:
    distributor_id: str
    distributor_name: str
    sku_id: str
    available_qty: int
    unit_price_inr: float
    delivery_estimate_hours: int
    cold_chain_capable: bool
    api_integrated: bool        # False = structured email fallback


@dataclass
class DistributorOrder:
    order_id: str
    distributor_id: str
    store_id: str
    items: list[dict[str, Any]]
    status: str                 # PLACED | CONFIRMED | IN_TRANSIT | DELIVERED | FAILED
    estimated_arrival_utc: str | None
    cold_chain_intact: bool | None
    tracking_available: bool


class DistributorMCPServer:
    """
    Interface between the AI reasoning layer and MedChain's distributor network.
    """

    def __init__(self, base_url: str = settings.mcp_distributor_url) -> None:
        self._base = base_url.rstrip("/")

    # ── Read tools ─────────────────────────────────────────────────────────────

    async def check_distributor_stock(
        self,
        sku_id: str,
        quantity_needed: int,
        delivery_zone: str,
        cold_chain_required: bool = False,
    ) -> list[DistributorStock]:
        """
        Returns availability across all distributors for a specific SKU.
        Filters for cold chain capability when required.
        """
        params: dict[str, Any] = {
            "sku_id": sku_id,
            "qty": quantity_needed,
            "zone": delivery_zone,
            "cold_chain": cold_chain_required,
        }
        raw = await self._get("/stock/check", params)
        return [DistributorStock(**d) for d in raw.get("distributors", [])]

    async def get_price_comparison(
        self,
        sku_id: str,
        quantity: int,
    ) -> list[dict[str, Any]]:
        """
        Returns per-unit pricing across all distributors including bulk discounts.
        Used by MERIDIAN and PULSE for procurement cost optimisation.
        """
        raw = await self._get("/pricing/compare", {"sku_id": sku_id, "qty": quantity})
        return raw.get("options", [])

    async def get_delivery_status(self, order_id: str) -> dict[str, Any]:
        """Returns live delivery tracking for an in-flight order."""
        raw = await self._get("/orders/status", {"order_id": order_id})
        return raw

    async def get_supply_disruption_alerts(self, sku_ids: list[str] | None = None) -> list[dict[str, Any]]:
        """
        Returns active supply disruption alerts (manufacturer shortages,
        logistics delays, regulatory holds).
        """
        params: dict[str, Any] = {}
        if sku_ids:
            params["sku_ids"] = ",".join(sku_ids)
        raw = await self._get("/disruptions", params)
        return raw.get("alerts", [])

    # ── Write tools ────────────────────────────────────────────────────────────

    async def submit_order(
        self,
        distributor_id: str,
        store_id: str,
        items: list[dict[str, Any]],
        urgency: str,
        cold_chain_required: bool,
        authority_level: str,
        decision_id: str,
    ) -> DistributorOrder | dict[str, Any]:
        """
        Submits a purchase order to a distributor.
        For API-integrated distributors: direct REST call.
        For others: structured email generated by this server.
        """
        payload = {
            "distributor_id": distributor_id,
            "store_id": store_id,
            "items": items,
            "urgency": urgency,
            "cold_chain_required": cold_chain_required,
            "authority_level": authority_level,
            "decision_id": decision_id,
        }
        raw = await self._post("/orders/submit", payload)
        if "order_id" in raw:
            return DistributorOrder(**raw)
        return raw

    async def flag_supply_disruption(
        self,
        sku_id: str,
        distributor_id: str,
        disruption_type: str,
        decision_id: str,
    ) -> dict[str, Any]:
        """
        Reports a supply disruption and triggers alternative sourcing search.
        Returns alternative distributors and alternative SKU suggestions.
        """
        return await self._post("/disruptions/flag", {
            "sku_id": sku_id,
            "distributor_id": distributor_id,
            "disruption_type": disruption_type,
            "decision_id": decision_id,
        })

    # ── Internal HTTP helpers ──────────────────────────────────────────────────

    async def _get(self, path: str, params: dict[str, Any]) -> dict[str, Any]:
        url = f"{self._base}{path}"
        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                resp = await client.get(url, params=params)
                resp.raise_for_status()
                return resp.json()
        except Exception as exc:
            logger.warning("mcp_distributor_get_failed", path=path, error=str(exc))
            return {}

    async def _post(self, path: str, payload: dict[str, Any]) -> dict[str, Any]:
        url = f"{self._base}{path}"
        try:
            async with httpx.AsyncClient(timeout=20.0) as client:
                resp = await client.post(url, json=payload)
                resp.raise_for_status()
                return resp.json()
        except Exception as exc:
            logger.error("mcp_distributor_post_failed", path=path, error=str(exc))
            return {"error": str(exc)}
