"""
Audit Integration Layer.

Bridges the LangGraph workflow execution with the AuditLogger.
Provides structured audit hooks for every critical decision point.

Immutable audit trail:
  - Every NEXUS decision is recorded before execution
  - Every execution outcome is recorded after completion
  - CHRONICLE retrospective analysis updates outcome fields
  - All records are append-only JSONL (never deleted or modified in place)
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from graph.state import PharmaIQState
from utils.logger import get_logger, get_audit_logger

logger = get_logger("graph.audit")
audit = get_audit_logger()


async def record_cycle_start(state: PharmaIQState) -> str:
    """
    Record the start of a decision cycle.
    Returns a cycle_id that can be referenced throughout the cycle.
    """
    cycle_id = str(uuid.uuid4())
    await audit.record(
        agent="SYSTEM",
        event_type="CYCLE_START",
        domain="system",
        action="start_cycle",
        authority_level="AUTO",
        reasoning_summary=(
            f"Decision cycle {state.cycle_type} started. "
            f"Store: {state.store_id}, Zone: {state.zone_id}"
        ),
        data_sources=[state.signal_type or "scheduled"],
        confidence=1.0,
        critique_verdict=None,
        compliance_verdict=None,
        estimated_cost_lakh=0.0,
        extra={"cycle_id": cycle_id, "cycle_type": state.cycle_type},
    )
    logger.info(
        "audit_cycle_start",
        cycle_id=cycle_id,
        store_id=state.store_id,
        cycle_type=state.cycle_type,
    )
    return cycle_id


async def record_tier1_proposals(state: PharmaIQState, cycle_id: str) -> None:
    """Record all proposals generated by Tier 1 agents for this cycle."""
    for alert in state.cold_chain_alerts:
        await audit.record(
            agent="SENTINEL",
            event_type="TIER1_PROPOSAL",
            domain="cold_chain",
            action="cold_chain_alert",
            authority_level="PENDING_VALIDATION",
            reasoning_summary=alert.sentinel_recommendation[:500] if alert.sentinel_recommendation else "",
            data_sources=["cold_chain_mcp", "drug_stability_profiles"],
            confidence=1.0,
            critique_verdict=None,
            compliance_verdict=None,
            estimated_cost_lakh=0.0,
            extra={"cycle_id": cycle_id, "alert_id": alert.alert_id, "excursion_type": alert.excursion_type},
        )

    for gap in state.compliance_gaps:
        await audit.record(
            agent="AEGIS",
            event_type="TIER1_PROPOSAL",
            domain="staffing",
            action="compliance_gap",
            authority_level="PENDING_VALIDATION",
            reasoning_summary=gap.recommended_action if gap.recommended_action else "",
            data_sources=["hrms_mcp"],
            confidence=gap.aegis_confidence,
            critique_verdict=None,
            compliance_verdict=None,
            estimated_cost_lakh=0.0,
            extra={"cycle_id": cycle_id, "store_id": gap.store_id, "gap_type": gap.gap_type},
        )

    for item in state.expiry_risk_items:
        await audit.record(
            agent="MERIDIAN",
            event_type="TIER1_PROPOSAL",
            domain="inventory",
            action="expiry_intervention",
            authority_level="PENDING_VALIDATION",
            reasoning_summary=f"Risk score {item.risk_score:.2f}. Intervention: {item.recommended_intervention}",
            data_sources=["erp_mcp"],
            confidence=min(item.risk_score, 1.0),
            critique_verdict=None,
            compliance_verdict=None,
            estimated_cost_lakh=item.estimated_loss_lakh,
            extra={
                "cycle_id": cycle_id,
                "sku_id": item.sku_id,
                "batch_id": item.batch_id,
                "days_to_expiry": item.days_to_expiry,
            },
        )


async def record_validation_results(state: PharmaIQState, cycle_id: str) -> None:
    """Record all CRITIQUE and COMPLIANCE verdicts."""
    for verdict in state.critique_verdicts:
        await audit.record(
            agent="CRITIQUE",
            event_type="CRITIQUE_VERDICT",
            domain="validation",
            action="critique_validation",
            authority_level="AUTO",
            reasoning_summary=verdict.reasoning[:500] if verdict.reasoning else "",
            data_sources=["state"],
            confidence=verdict.overall_score / 10.0,
            critique_verdict=verdict.outcome,
            compliance_verdict=None,
            estimated_cost_lakh=0.0,
            extra={
                "cycle_id": cycle_id,
                "proposal_id": verdict.proposal_id,
                "agent_source": verdict.agent_source,
                "modifications_required": len(verdict.required_modifications),
            },
        )

    for verdict in state.compliance_verdicts:
        await audit.record(
            agent="COMPLIANCE",
            event_type="COMPLIANCE_VERDICT",
            domain="regulatory",
            action="compliance_verification",
            authority_level="AUTO",
            reasoning_summary=verdict.reasoning[:500] if verdict.reasoning else "",
            data_sources=["regulatory_kb"],
            confidence=verdict.compliance_confidence,
            critique_verdict=None,
            compliance_verdict=verdict.outcome,
            estimated_cost_lakh=0.0,
            extra={
                "cycle_id": cycle_id,
                "proposal_id": verdict.proposal_id,
                "regulatory_basis": verdict.regulatory_basis[:3],
                "blocking_issues": len(verdict.blocking_issues),
            },
        )


async def record_cycle_complete(state: PharmaIQState, cycle_id: str) -> None:
    """Record cycle completion summary."""
    await audit.record(
        agent="SYSTEM",
        event_type="CYCLE_COMPLETE",
        domain="system",
        action="complete_cycle",
        authority_level="AUTO",
        reasoning_summary=(
            f"Cycle {state.cycle_type} complete. "
            f"Approved: {len(state.nexus_priority_decisions)}, "
            f"Escalated: {len(state.pending_escalations)}, "
            f"Cold chain risk: {state.cold_chain_risk_level}"
        ),
        data_sources=[],
        confidence=1.0,
        critique_verdict=None,
        compliance_verdict=None,
        estimated_cost_lakh=sum(
            d.get("estimated_cost_lakh", 0.0)
            for d in state.nexus_priority_decisions
        ),
        extra={
            "cycle_id": cycle_id,
            "cycle_type": state.cycle_type,
            "approved_count": len(state.nexus_priority_decisions),
            "escalated_count": len(state.pending_escalations),
        },
    )
    logger.info("audit_cycle_complete", cycle_id=cycle_id, store_id=state.store_id)
